import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {hasLocale, NextIntlClientProvider, useMessages} from 'next-intl';
import { notFound } from 'next/navigation';
import '@/styles/globals.css'
import '@/styles/variables.css'
import {routing} from '@/i18n/routing';
import LanguageSwitcher from "@/components/LanguageSwitcher";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
                                               children,
                                               params
                                           }: {
    children: React.ReactNode;
    params: Promise<{locale: string}>;
}) {
    // Ensure that the incoming `locale` is valid
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale}>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </head>
            <body>
                <LanguageSwitcher/>
                <NextIntlClientProvider>
                    {children}
                    <Footer/>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}